---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=safe

- name: 'Upgrade the OS (apt-get dist-upgrade)'
  apt:
    upgrade: dist

- name: 'Install a list of packages'
  apt:
    pkg:
    - htop
    - curl
    - python3-dev

- name: 'Creates workspace'
  file:
    path: /home/pi/Workspace
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: 'Creates custom bin'
  file:
    path: /home/ubuntu/bin
    state: directory
    owner: pi
    group: pi
    mode: 0755    
    
- name: 'Add a line to .profile'
  ansible.builtin.lineinfile:
    path: /home/ubuntu/bin
    line: PATH=$PATH:~/bin
    create: yes

- name: 'Add a line to .profile'
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: alias ll='ls -l'
    create: yes

- name: 'Install Docker'
  shell: curl -sSL https://get.docker.com | sh
  async: 1
  poll: 0
  ignore_errors: true
  
- name: 'rootless mode for docker'
  shell: sudo usermod -aG docker pi
  async: 1
  poll: 0
  ignore_errors: true

- name: 'Reboot'
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true  
  
- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false
